apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: saloon-system
  labels:
    app: booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: booking-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://zipkin:9411"
