apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: saloon-system
  labels:
    app: booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: booking-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: API_GATEWAY_URL
              value: "/"
            - name: MANAGEMENT_OTLP_TRACING_ENDPOINT
              value: "http://tempo.observability.svc.cluster.local:4318/v1/traces"
            - name: MANAGEMENT_TRACING_PROPAGATION_TYPE
              value: "w3c"
            - name: DB_USERNAME
              value: "saloon_user"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: saloon-secrets
                  key: db-password
            - name: DB_NAME
              value: "saloon_service"
            - name: DB_HOST
              value: "mysql-service"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: saloon-secrets
                  key: jwt-secret
            - name: IDENTITY_SERVICE_URL
              value: "http://identity-service:8082"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
